### ISSUE TITLE
Error linking executable to v4l2_ioctl

### ISSUE THREAD

**Issue by rtavera** [turcofran/omfootctrl#2]
Hello,
I'm exited with this project and I tried to compile it on a Linux Mint 17.3 32bit. make proccess get 100%, but fails when linking the executable, this is the error trace:

[ 20%] Building CXX object CMakeFiles/cvOM.dir/footcontroller.cpp.o
[ 40%] Building CXX object CMakeFiles/cvOM.dir/ocv.cpp.o
[ 60%] Building CXX object CMakeFiles/cvOM.dir/osc.cpp.o
[ 80%] Building CXX object CMakeFiles/cvOM.dir/midi.cpp.o
[100%] Building CXX object CMakeFiles/cvOM.dir/main.cpp.o
Linking CXX executable cvOM
/usr/bin/ld: CMakeFiles/cvOM.dir/ocv.cpp.o: referencia sin definir al símbolo 'v4l2_ioctl'
/usr/lib/gcc/i686-linux-gnu/4.8/../../../i386-linux-gnu/libv4l2.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: **\* [cvOM] Error 1
make[1]: **\* [CMakeFiles/cvOM.dir/all] Error 2
make: **\* [all] Error 2

Any clue?

Regards!

**Comment by turcofran** [comment]
Please make sure you have installed the libv4l-dev package.
The method 'v4l2_ioctl' is used to communicate with the camera by using the v4l2 API.
If you still have problems with that, a workaround would be to comment the lines that use it, and try to configure the camera with v4l-conf or qv4l2 (GUI).
BTW, do you speak spanish?

**Comment by rtavera** [comment]
Hola, gracias por el consejo, voy a intentarlo al llegar a casa (me esperan
más de dos horas de camino)

Que buen proyecto, quiero usarlo precisamente con sooperlooper, aunque
supongo que también puedo mapear a guitarix o rakarrack.

Gracias nuevamente

**Comment by turcofran** [comment]
I have tried the expression pedal with the Guitarix's wah-wah and it works fine! I mean, by sending MIDI commands...
Let me know how it works!

**Comment by rtavera** [comment]
Well, no luck compiling :( , I have the package installed, I also tryed on
an Ubuntu 16.04 64bit with same results, now I'm downloading Debian, just
to give it a chance....

2016-06-22 17:59 GMT-05:00 turcofran notifications@github.com:

**Comment by rtavera** [comment]
Wow!, compiled on Debian!, now, lets play with this software

Thank you

2016-06-22 18:07 GMT-05:00 turcofran notifications@github.com:

**Comment by turcofran** [comment]
Great! Sorry I couldn't give you any help, I'm moving out to another city.. :S.
Regarding your previous error, here you can get some clues:
http://stackoverflow.com/questions/19901934/strange-linking-error-dso-missing-from-command-line
http://askubuntu.com/questions/484552/error-while-compiling-opencv-in-ubuntu-14-04
It seems to be something with the dependencies and/or linker options.
Anyway, every cloud has a silver lining, now you are using Debian! 
Cheer!
